---
- name: Install packages
  community.general.pacman:
    update_cache: yes     # equivalent to 'pacman -Sy'
    name: 
      - base-devel        # 'group' - set of packages used for compiling
      - bat               # 'cat' replacement written in rust
      - fd                # 'find' replacement written in rust
      - fzf               # a command line fuzzy finder
      - git               # scm
      - htop              # interactive system monitoring
      - iotop             # disk and IO monitoring
      - lm_sensors        # tools and drivers for monitoring temperatures, voltages
      - man-db            # man-pages 
      - man-pages         # man-pages 
      - p7zip             # archive tool 
      - pacman-contrib    # pacman-tools
      - plocate           # unix tool for finding files quickly
      - ripgrep           # grep replacment written in rust
      - smartmontools     # disk health status
      - sudo              # run commands as root or another user
      - zsh               # unix shell, alternative to bash
    state: present

- name: Ensure plocate-updatedb.timer is started and enabled at boot
  ansible.builtin.systemd:
    name: plocate-updatedb.timer # required as of docs
    state: started
    enabled: yes

- name: Create symlink vi
  ansible.builtin.file:
    src: /usr/bin/vim
    dest: /usr/bin/vi
    state: link

- name: Ensure scripts directory exists
  ansible.builtin.file:
    path: /root/scripts
    state: directory
    owner: root
    group: root 
    mode: '755'

- name: Update pacman mirrors script
  ansible.builtin.copy:
    src: files/pacman-new-mirrorlist.sh
    dest: /root/scripts/pacman-new-mirrorlist.sh
    owner: root
    group: root
    mode: '700'
