---
- name: Install packages
  ansible.builtin.pacman:
    update_cache: yes
    name:
      - certbot
      - certbot-dns-linode
    state: present

- name: Copy certbot dir 
  ansible.builtin.copy:
    src: certbot
    dest: /root/
    owner: root
    group: root
    mode: '700'

- name: Copy certbot systemd service file
  ansible.builtin.copy:
    src: files/certbot.service
    dest: /etc/systemd/system/certbot.service
    owner: root
    group: root
    mode: '644'

- name: Add systemd timer for refreshing wildcard cert 
  ansible.builtin.copy:
    src: files/certbot.timer
    dest: /etc/systemd/system/certbot.timer
    owner: root
    group: root
    mode: '644'

- name: Ensure certbot.timer is started and enabled at boot
  ansible.builtin.systemd:
    name: certbot.timer
    state: started
    enabled: yes

- name: Run get-certs
  command: "/root/certbot/get-certs.sh"
